In [2]:
import os
import sys
import numpy as np
import pandas as pd
import matplotlib as mlp
from matplotlib import pyplot as plt
import seaborn as sns
%matplotlib inline
mlp.style.use("seaborn")
import statsmodels
import statsmodels.api as sm

import warnings
warnings.filterwarnings("ignore")

In [3]:
ie_data = pd.read_excel("../data/ie_data.xls", sheet_name="Data", skiprows=7)
ie_data.drop(ie_data.tail(1).index, inplace=True)
ie_data.rename(columns={"Yield": "Excess_CAPE_Yield", "Real Return": "Real_Returns_Equity", "Real Return.1": "Real_Returns_Bond", "Returns.2": "Excess_Real_Returns_Equity"}, inplace=True)
print(ie_data.columns)
ie_data.head()

Index(['Date', 'P', 'D', 'E', 'CPI', 'Fraction', 'Rate GS10', 'Price',
       'Dividend', 'Price.1', 'Earnings', 'Earnings.1', 'CAPE', 'Unnamed: 13',
       'TR CAPE', 'Unnamed: 15', 'Excess_CAPE_Yield', 'Returns', 'Returns.1',
       'Real_Returns_Equity', 'Real_Returns_Bond',
       'Excess_Real_Returns_Equity'],
      dtype='object')

,Date,P,D,E,CPI,Fraction,Rate GS10,Price,Dividend,Price.1,...,CAPE,Unnamed: 13,TR CAPE,Unnamed: 15,Excess_CAPE_Yield,Returns,Returns.1,Real_Returns_Equity,Real_Returns_Bond,Excess_Real_Returns_Equity
0,1871.01,4.44,0.26,0.4,12.4641,1871.041667,5.32,97.250271,5.694836,97.250271,...,NaN,NaN,NaN,NaN,NaN,1.004177,1.000000,0.130609,0.092504,0.038106
1,1871.02,4.5,0.26,0.4,12.8446,1871.125000,5.32333,95.644049,5.526101,96.104557,...,NaN,NaN,NaN,NaN,NaN,1.004180,0.974424,0.130858,0.094635,0.036224
2,1871.03,4.61,0.26,0.4,13.035,1871.208333,5.32667,96.551327,5.445411,97.472173,...,NaN,NaN,NaN,NaN,NaN,1.004183,0.964209,0.130951,0.096186,0.034765
3,1871.04,4.74,0.26,0.4,12.5592,1871.291667,5.33,103.034548,5.651684,104.492692,...,NaN,NaN,NaN,NaN,NaN,1.004185,1.004919,0.122056,0.090972,0.031084
4,1871.05,4.86,0.26,0.4,12.2738,1871.375000,5.33333,108.099637,5.783108,110.118209,...,NaN,NaN,NaN,NaN,NaN,1.004188,1.032591,0.122638,0.089488,0.033150